### ISSUE TITLE
deserialize  

### ISSUE THREAD

**Issue by kyoxsky** [marcel-goldschen-ohm/QtPropertySerializer#2]
How to deserialize  QList<QObject*> ?  thanks.

**Comment by marcel-goldschen-ohm** [comment]
At the moment that is not directly possible. As of now, you could give all the objects in the list a common parent and then serialize/deserialize the parent object. The current serialization only handles the QObject tree structure. If you would like to add code for the list that would be great.  Recently aegeon added to the function addMappedData() to allow serializing QVariants that hold a list of QObject*, so that will likely help you in this regard.

**Comment by marcel-goldschen-ohm** [comment]
I added a couple of convenience functions for QList<QObject*>. Basically they just loop and serialize/deserialize each QObject* as normal.
